feat: add husky and lint-staged
- Update doc, README.md and CONTRIBUTING.md

- Now every git commit will auto-formatting with Biome on staged files using lint-staged

- And every git push will run
> fuwari@0.0.1 check /home/iarch/code/astro/astro-fuwari-blog
> astro check

20:19:52 [content] Syncing content
20:19:52 [content] Synced content
20:19:52 [types] Generated 386ms
20:19:52 [check] Getting diagnostics for Astro files in /home/iarch/code/astro/astro-fuwari-blog...
[96msrc/components/Navbar.astro[0m:[93m54[0m:[93m14[0m - [91merror[0m[90m ts(2322): [0mType '{ "client:only": string; }' is not assignable to type 'IntrinsicAttributes & Record<string, never>'.
  Type '{ "client:only": string; }' is not assignable to type 'Record<string, never>'.
    Property 'client:only' is incompatible with index signature.
      Type 'string' is not assignable to type 'never'.

[7m54[0m             <LightDarkSwitch client:only="svelte"></LightDarkSwitch>
[7m  [0m [91m             ~~~~~~~~~~~~~~~[0m

[96msrc/pages/archive.astro[0m:[93m12[0m:[93m19[0m - [91merror[0m[90m ts(2322): [0mType 'PostForList[]' is not assignable to type 'Post[]'.
  Type 'PostForList' is not assignable to type 'Post'.
    The types of 'data.category' are incompatible between these types.
      Type 'string | null' is not assignable to type 'string | undefined'.
        Type 'null' is not assignable to type 'string | undefined'.

[7m12[0m     <ArchivePanel sortedPosts={sortedPostsList} client:only="svelte"></ArchivePanel>
[7m  [0m [91m                  ~~~~~~~~~~~[0m

[96msrc/plugins/expressive-code/language-badge.ts[0m:[93m10[0m:[93m16[0m - [93mwarning[0m[90m ts(6133): [0m'_cssVar' is declared but its value is never read.

[7m10[0m   baseStyles: ({ _cssVar }) => `
[7m  [0m [93m               ~~~~~~~~~~~[0m

Result (55 files):
- 2 errors
- 0 warnings
- 1 hint

 ELIFECYCLE  Command failed with exit code 1. and
> fuwari@0.0.1 type-check /home/iarch/code/astro/astro-fuwari-blog
> tsc --noEmit --isolatedDeclarations

src/constants/constants.ts(6,14): error TS9010: Variable must have an explicit type annotation with --isolatedDeclarations.
src/constants/constants.ts(11,14): error TS9010: Variable must have an explicit type annotation with --isolatedDeclarations.
src/content/config.ts(26,9): error TS9013: Expression type can't be inferred with --isolatedDeclarations.
src/content/config.ts(27,8): error TS9013: Expression type can't be inferred with --isolatedDeclarations.
src/pages/rss.xml.ts(19,23): error TS9007: Function must have an explicit return type annotation with --isolatedDeclarations.
src/plugins/expressive-code/custom-copy-button.ts(4,17): error TS9007: Function must have an explicit return type annotation with --isolatedDeclarations.
src/plugins/expressive-code/language-badge.ts(6,17): error TS9007: Function must have an explicit return type annotation with --isolatedDeclarations.
src/utils/content-utils.ts(20,23): error TS9007: Function must have an explicit return type annotation with --isolatedDeclarations.
src/utils/setting-utils.ts(30,17): error TS9007: Function must have an explicit return type annotation with --isolatedDeclarations.
src/utils/url-utils.ts(4,17): error TS9007: Function must have an explicit return type annotation with --isolatedDeclarations.
src/utils/url-utils.ts(42,17): error TS9007: Function must have an explicit return type annotation with --isolatedDeclarations.
 ELIFECYCLE  Command failed with exit code 2.. Prevent push if found any error